# Generated by Django 2.0.7 on 2018-07-12 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('number_registry', '0003_auto_20180711_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='dedicaition',
            new_name='dedication',
        ),
    ]
