# Generated by Django 2.0.7 on 2018-07-17 16:54

from django.db import migrations, models
import number_registry.models


class Migration(migrations.Migration):

    dependencies = [
        ('number_registry', '0006_entry_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='name',
            field=models.CharField(max_length=100, validators=[number_registry.models.validateUniqueName]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='number',
            field=models.BigIntegerField(validators=[number_registry.models.validate_div3, number_registry.models.validateUniqueNumber]),
        ),
    ]
